
development:
   adapter: postgresql
   encoding: utf-8
   host: localhost
   database: local_database
   pool: 5
   username: rails
   password: rails

production:
   adapter: postgresql
   encoding: utf-8
   database: remote_database
   pool: 5
   username: rails
   password: rails
